# Generated by Django 3.2.4 on 2021-06-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=200)),
                ('texto', models.TextField()),
            ],
        ),
    ]
